"""User and Access_project update

Revision ID: dcbc3eeb5cd5
Revises: 758b40b14780
Create Date: 2024-04-01 12:22:31.385321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbc3eeb5cd5'
down_revision = '758b40b14780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
